Fix obsolete api waring [#260] issue to support android project
novoda/bintray-release pull request #296
Opened 2019-10-10 09:29 UTC by KaelLuo

2019-10-10 09:29 UTC, hal9002 commented
Can one of the admins review this PR?

2019-10-10 09:48 UTC, StefMa commented
Is a task in the properties?
Why not checking if this task is available via the Task Container?

On Thu, Oct 10, 2019, 11:29 AM hal 9002 <notifications@github.com> wrote:

> Can one of the admins review this PR?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/novoda/bintray-release/pull/296?email_source=notifications&email_token=ACOBQ67SMVDNQSCZRQT7TPLQN3YXHA5CNFSM4I7KIXJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA3SCHY#issuecomment-540483871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOBQ62C5C5S6QPQQG63SITQN3YXHANCNFSM4I7KIXJA>
> .
>

2019-10-10 11:23 UTC, KaelLuo commented
Hey StefMa, thanks for the quick review.  
`variant` is not a task, it's actually passed from "ReleasePlugin#attachArtifacts" function within this code 
```
project.android.libraryVariants.all { variant ->
                String publicationName = variant.name
                MavenPublication publication = createPublication(publicationName, project, extension)
                new AndroidAttachments(publicationName, project, variant).attachTo(publication)
            }
```
In some other popular library, they also fix this kind of issue in same way, a similar fix discuss attached here:
https://github.com/google/protobuf-gradle-plugin/issues/295

2019-11-28 23:08 UTC, mr-archano requested changes
Thanks @KaelLuo for providing this. Just left a small remark.

2019-11-28 23:08 UTC, mr-archano commented on plugin/core/src/main/groovy/com/novoda/gradle/release/internal/AndroidAttachments.groovy
> +                javadoc.source = variant.javaCompileProvider.get().source
I would prefer to extract a little method where to put this if statement (like we have already done in [another plugin](https://github.com/novoda/gradle-static-analysis-plugin/blame/master/plugin/src/main/groovy/com/novoda/staticanalysis/internal/CodeQualityConfigurator.groovy#L133-L139)) so we can remove some duplication

2022-02-11 06:01 UTC, closed without merging

2022-02-11 06:02 UTC, KaelLuo commented
您收到此邮件表示您发送的邮件我已经收到，会尽快给您回复，请耐心等候，亲